{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helloapp.serviceAccountName" . }}
  labels:
    {{- include "helloapp.labels" . | nindent 4 }}
# automountServiceAccountToken is set to false by default.
# Most applications don't need to talk to the Kubernetes API.
# Mounting the token exposes it to theft if the pod is compromised.
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
